server:
  port: 8030

artemis:
  mq:
    broker-url: tcp://localhost:61616
    user: username
    password: password
  sendByteMessage: true

rate:
  queue: CNR.GLOBE.RATESPUBL.V4.OUT
  subscription: MOCHEGOV

account:
  queue: INT.NI.ACCNT.PUB

ae:
  queue:
    prototype:
      in: AE.PROTOTYPE.IN
      out: AE.PROTOTYPE.OUT
