server:
  port: 8030

artemis:
  mq:
    broker-url: tcp://localhost:61616
    user: username
    password: password

rate:
  queue: CNR.GLOBE.RATESPUBL.V4.OUT
  subscription: MOCHEGOV

account:
  queue: INT.NI.ACCNT.PUB

